### ISSUE TITLE
An option for choosing the available dictionaries

### ISSUE THREAD

**Issue by M157q** [M157q/zdict#21]
+ Use Yahoo dictionary as default.
+ Add an option for users choosing one of the available dictionaries.
+ If users not giving an argument for this option, the program should list out all available dictionaries.
+ There should be an argument "all" within this option for showing all results from every available dictionaries of the words queried by users.
+ The available dictionaries list should not be modified manually, instead, it should be parsed from the directory which stores all of the available dictionary classes (`zdict/dictionaries/`). (ref https://github.com/M157q/zdict/commit/1ef84c386e8cf8b9241477b76b6f50efeef558e9)

**Comment by wdv4758h** [comment]
We can make a MetaDictionary class to handle multiple dictionaries. It can have a list of dictionaries, then query by a for loop and display the result.

**Comment by wdv4758h** [comment]
++++++++++++++++++++

**Comment by M157q** [comment]
ref #44
