### ISSUE TITLE
zdict vim plugin

### ISSUE THREAD

**Issue by pi314** [M157q/zdict#36]
[plan] Press, say `<leader>b`, on a word, and vim shows a vertical split to show the result, just like The-NERD-Tree

**Comment by M157q** [comment]
I think this should be another project like `zdict.vim` as a vim plugin which depends on this project.

**Comment by iblis17** [comment]
How about create a new org called 'zdict'; collecting all the relative project?

**Comment by M157q** [comment]
@iblis17 I'll consider about it if we come to that time. I mean, we only have this project currently.

If #36, #33 really happens.

**Comment by M157q** [comment]
wow, I saw this.
https://github.com/pi314/zdict.vim
